default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: root
  host: localhost

production:
  <<: *default

development:
  <<: *default
  database: 'school_test_development'